- name: Deploy App
  run: |
    ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
      sudo mkdir -p /var/www/my-node-app
      sudo chown -R $USER:$USER /var/www/my-node-app
      cd /var/www/my-node-app
      
      git config --global --add safe.directory /var/www/my-node-app
      if [ ! -d ".git" ]; then
        git clone https://github.com/YOUR_GITHUB_USERNAME/YOUR_REPO.git .
      fi
      git pull origin main

      if ! command -v node &> /dev/null; then
        curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
        sudo apt-get install -y nodejs
      fi

      npm install --production

      if ! command -v pm2 &> /dev/null; then
        npm install -g pm2
      fi

      pm2 restart my-node-app || pm2 start app.js --name my-node-app
    EOF
