name: Node.js Build & Deploy

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test

      - name: Build Project
        run: npm run build

      - name: Create a file
        run: echo "I won't live long" > my_file.txt


        

      - name: upload build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: my_file.txt # Ensure this path is correct and exists

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Download build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-output
          path: my_file.txt

      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /var/www/my-node-app
            git pull origin master
            npm install --production
            pm2 restart my-node-app
